courses/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	
	url(r'^mine/$',
		views.ManageCourseListView.as_view(),
		name="manage_course_list"),

	url(r'^create/$',
		views.CourseCreateView.as_view(),
		name="course_create"),

	url(r'^(?P<pk>\d+)/edit/$',
		views.CourseUpdateView.as_view(),
		name="course_edit"),

	url(r'^(?P<pk>\d+)/delete/$',
		views.CourseDeleteView.as_view(),
		name="course_delete"),

	# Para el formset
	url(r'^(?P<pk>\d+)/module/$',
		views.CourseModuleUpdateView.as_view(),
		name="course_module_update"),

	# url for content
	url(r'^module/(?P<module_id>\d+)/content/(?P<model_name>\w+)/create/$',
		views.ContentCreateUpdateView.as_view(),
		name="module_content_create"),

	url(r'^module/(?P<module_id>\d+)/content/(?P<model_name>\w+)/(?P<id>\d+)/$',
		views.ContentCreateUpdateView.as_view(),
		name="module_content_update"),

	# delete content
	url(r'^content/(?P<id>\d+)/delete/$',
		views.ContentDeleteView.as_view(),
		name="module_content_delete"),

	# crm content
	url(r'^module/(?P<module_id>\d+)/$',
		views.ModuleContentListView.as_view(),
		name="module_content_list"),

	# Reordenar modulos y contenidos
	url(r'^module/order/$',
		views.ModuleOrderView.as_view(),
		name="module_order"),

	url(r'^content/order/$',
		views.ContentOrderView.as_view(),
		name="content_order"),

#list and detail views

	url(r'^subject/(?P<subject>[\w-]+)/$',
		views.CourseListView.as_view(),
		name='course_list_subject'),

	url(r'^(?P<slug>[\w-]+)$',
		views.CourseDetailView.as_view(),
		name="course_detail"),

	url(r'^$',
		views.Subjects.as_view(),
		name="subject_list"),

	#
#subjects
	url(r'^subjects/(?P<slug>[\w-]+)$', views.SubjectDetail.as_view(), name="subject_detail"),
    url(r'^subjects/(?P<slug>[\w-]+)/(?P<course_slug>[\w-]+)$', views.SubjectDetail.as_view(), 
    	name="subject_detail_with_course"),

]

galaxy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import urls as mainUrls
from courses import urls as coursesUrls
from accounts import urls as accountsUrls
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.views import password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from students import urls as studentsUrls


urlpatterns = [
    
    url(r'^students/',
        include(studentsUrls, namespace="students")),

    url(r'^accounts/', 
        include(accountsUrls)),

    url(r'^admin/', admin.site.urls),

    url(r'^courses/',
        include(coursesUrls, namespace="courses")),

    url(r'^',
        include(mainUrls)),

    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}
        ),
]

main/urls.py
from django.conf.urls import url


urlpatterns = [

]

courses/models.py
from django.db import models
from django.contrib.auth.models import User

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from .fields import OrderField

from embed_video.fields import EmbedVideoField

class Subject(models.Model):
	title = models.CharField(max_length=140)
	slug = models.SlugField(max_length=200, unique=True)
	image = models.ImageField(upload_to="images/subjects", blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	video = EmbedVideoField(blank=True, null=True)

	class Meta:
		ordering = ('title',)

	def __str__(self):
		return self.title

class Course(models.Model):
	owner = models.ForeignKey(User, related_name='courses_created')
	subject = models.ForeignKey(Subject, related_name='courses')
	title = models.CharField(max_length=200)
	slug = models.SlugField(max_length=200, unique=True)
	overview = models.TextField(blank=True)
	created = models.DateTimeField(auto_now=True)
	students = models.ManyToManyField(User, related_name='courses_joined',blank=True)
	

	class Meta:
		ordering = ('-created',)

	def __str__(self):
		return self.title

class Module(models.Model):
	course = models.ForeignKey(Course, related_name='modules')
	title = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	order = OrderField(blank=True, for_fields=['course'])

	class Meta:
		ordering = ['order']

	def __str__(self):
		return '{}. {}'.format(self.order, self.title)

class Content(models.Model):
	module = models.ForeignKey(Module, related_name='contents')
	# content_type = models.ForeignKey(ContentType)
	content_type = models.ForeignKey(ContentType, limit_choices_to={'model__in':(
		'text',
		'video',
		'image',
		'file')})
	object_id = models.PositiveIntegerField()
	item = GenericForeignKey('content_type', 'object_id')
	order = OrderField(blank=True, for_fields=['module'])

	class Meta:
		ordering = ['order']

# Para renderizar diferentes tipos de contenido
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe

class ItemBase(models.Model):
	owner = models.ForeignKey(User, related_name='%(class)s_related')
	title = models.CharField(max_length=250)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True

	def __str__(self):
		return self.title

	def render(self):
		return render_to_string('courses/content/{}.html'.format(self._meta.model_name), {'item':self})
		


class Text(ItemBase):
	content = models.TextField()

class File(ItemBase):
	file = models.FileField(upload_to='files')

class Image(ItemBase):
	file = models.FileField(upload_to='images')

class Video(ItemBase):
	url = models.URLField()

courses/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Course, Module


ModuleFormset = inlineformset_factory(
	Course,
	Module,
	fields=[
	'id',
	'title',
	'description'
	],
	extra=2,
	can_delete=True)

courses/views.py
from django.views.generic import View
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.generic.base import TemplateResponseMixin, View
from .forms import ModuleFormset

# content to modules with generic view
from django.forms.models import modelform_factory
from django.apps import apps
from .models import Module, Content, Subject

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Course, Module, Content

from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from braces.views import LoginRequiredMixin, PermissionRequiredMixin, CsrfExemptMixin, JsonRequestResponseMixin

# Para lista y detalle 
from django.db.models import Count
from .models import Subject

# Para suscribirse a un courso
from students.forms import CourseEnrollForm


class OwnerMixin(object):
	def get_queryset(self):
		qs = super(OwnerMixin, self).get_queryset()
		return qs.filter(owner=self.request.user)

class OwnerEditMixin(object):
	def form_valid(self, form):
		form.instance.owner = self.request.user
		return super(OwnerEditMixin, self).form_valid(form)

class OwnerCourseMixin(OwnerMixin, LoginRequiredMixin):
	model = Course

class OwnerCourseEditMixin(OwnerCourseMixin, OwnerEditMixin):
	fields = ['subject', 'title', 'slug', 'overview']
	success_url = reverse_lazy('manage_course_list')
	template_name = 'courses/manage/course/form.html'


class ManageCourseListView(OwnerCourseMixin, ListView):
	template_name = 'courses/manage/course/list.html'

class CourseCreateView(PermissionRequiredMixin, OwnerCourseEditMixin, CreateView):
	permission_required = 'courses.add_course'

class CourseUpdateView(PermissionRequiredMixin, OwnerCourseEditMixin, UpdateView):
	permission_required = 'courses.change_course'

class CourseDeleteView(PermissionRequiredMixin, OwnerCourseMixin, DeleteView):
	template_name = 'courses/manage/course/delete.html'
	success_url = reverse_lazy('manage_course_list')
	permission_required = 'courses.delete_course'


# Para el crm

class CourseModuleUpdateView(TemplateResponseMixin, View):
	template_name = 'courses/manage/module/formset.html'
	course = None

	def get_formset(self, data=None):
		return ModuleFormset(instance=self.course, data=data)

	def dispatch(self, request, pk):
		self.course = get_object_or_404(Course, id=pk, owner=request.user)
		return super(CourseModuleUpdateView, self).dispatch(request, pk)

	def get(self, request, *args, **kwargs):
		formset = self.get_formset()
		return self.render_to_response({'course':self.course,
			'formset':formset})

	def post(self, request, *args, **kwargs):
		formset = self.get_formset(data=request.POST)
		if formset.is_valid():
			formset.save()
			return redirect('courses:manage_course_list')
		return self.render_to_response({'course':self.course,
			'formset':formset})

# Generic view for content
class ContentCreateUpdateView(TemplateResponseMixin, View):
	module = None
	model = None
	obj = None
	tipos = ['text', 'video', 'image', 'file']
	template_name = 'courses/manage/content/form.html'

	def get_model(self, model_name):
		print("lo que viene:", model_name)
		if model_name in ['text', 'video', 'image', 'file']:
			print('simon')
			return apps.get_model(app_label='courses',
				model_name=model_name)

		else:
			print('nel')
			return None


	def get_form(self, model, *args, **kwargs):
		Form  = modelform_factory(model, exclude=['owner','order','created','updated'])
		return Form(*args, **kwargs)

	def dispatch(self, request, module_id, model_name, id=None):
		print('dispatch:', module_id)
		self.module = get_object_or_404(Module, id=module_id, course__owner=request.user)
		# self.model = self.get_model(model_name)
		self.model = self.get_model(model_name)
		if id:
			self.obj = get_object_or_404(self.model, id=id, owner=request.user)
		return super(ContentCreateUpdateView, self).dispatch(request, module_id, model_name, id)

	def get(self, request, module_id, model_name, id=None, *args, **kwargs):
		print('entre al get')
		form = self.get_form(self.model, instance=self.obj)
		print(form)
		return self.render_to_response({'form':form, 'object':self.obj})



	def post(self, request, module_id, module_name, id=None):
		form = self.get_form(self.model, instance=self.obj, data=request.POST,
			files=request.FILES)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.owner = request.user
			obj.save()
			if not id:
				# nuveo contenido
				Content.objects.create(module=self.module, item=obj)
				return redirect('courses:module_content_list', self.module.id)
			return redirect('courses:module_content_list', self.module.id)
		return self.render_to_response({'form':form, 'object':self.obj})

# content delete

class ContentDeleteView(View):
	def post(self, request, id):
		content = get_object_or_404(Content, id=id,
			module__course__owner=request.user)
		module = content.module
		content.item.delete()
		content.delete()
		return redirect('courses:module_content_list', module.id)


# CMR para content

class ModuleContentListView(TemplateResponseMixin, View):
	template_name = 'courses/manage/module/content_list.html'

	def get(self, request, module_id):
		module = get_object_or_404(Module, id=module_id, course__owner=request.user)
		return self.render_to_response({'module':module})
		





# class ManageCourseListView(ListView):
# 	model = Course
# 	template_name = 'courses/manage/course/list.html'

# 	def get_queryset(self):
# 		qs = super(ManageCourseListView, self).get_queryset()
# 		return qs.filter(owner=self.request.user)

# List and Detail View
class CourseListView(TemplateResponseMixin, View):
	model = Course
	template_name = 'courses/course/list.html'

	def get(self, request, subject=None):
		subjects = Subject.objects.annotate(
			total_courses=Count('courses'))
		courses = Course.objects.annotate(
			total_modules=Count('modules'))
		if subject:
			subject = get_object_or_404(Subject, slug=subject)
			courses = courses.filter(subject=subject)
		return self.render_to_response({'subjects':subjects,
			'subject':subject,
			'courses':courses})

class CourseDetailView(DetailView):
	model = Course
	template_name = 'courses/course/detail.html'

	def get_context_data(self, **kwargs):
		context = super(CourseDetailView, self).get_context_data(**kwargs)
		context['enroll_form'] = CourseEnrollForm(initial={'course':self.object})
		return context


# Reordenar modulos y contenidos en el CRM (AJAX)
class ModuleOrderView(CsrfExemptMixin, JsonRequestResponseMixin, View):
	def post(self, request):
		for id, order in self.request_json.items():
			Module.objects.filter(id=id, course__owner=request.user).update(order=order)
		return self.render_json_response({'saved':'OK'})

class ContentOrderView(CsrfExemptMixin, JsonRequestResponseMixin, View):
	def post(self, request):
		for id, order in self.request_json.items():
			Content.objects.filter(id=id, module__course__owner=request.user).update(order=order)
			return self.render_json_response({'saved':'OK'})


#List of Subjects
class Subjects(View):

	def get(self,request):
		template_name = 'subjects/list.html'
		subjects = Subject.objects.annotate(no_courses=Count('courses'))
		context = {'subjects':subjects}
		return render(request, template_name, context)

#Detail of Subject
class SubjectDetail(View):
	def get(self,request, slug, course_slug=None):
		template_name = 'subjects/detail.html'
		subject = Subject.objects.get(slug = slug)
		languajes = Subject.objects.all().exclude(title=subject.title)
		courses = Course.objects.filter(subject = subject)
		if course_slug != None:
			course_selected = Course.objects.get(slug = course_slug)
			modules = Module.objects.filter(course = course_selected)
			context = {
			'subject': subject,
			'courses': courses,
			'course_selected':course_selected,
			'modules':modules,
			'languajes':languajes
			}
		else:
			context = {
			'subject': subject,
			'courses': courses,
			'languajes':languajes
			}

		return render(request, template_name, context)

courses/templates/subjects/detail.html
{% extends "base2.html" %}

{% load embed_video_tags %}
{% block content %}

	<style>
		.top{
			padding-top: 10%;
		}
		.top-mitad{
			padding-top: 5%
		}

		.remove-margin{
			margin: 0 !important;
			padding: 0 !important;
		}

		.top-all{
			margin-left: 5%;
			margin-right: 2%;
		}

		.nav_higher{
			height: 10% !important;
		}

		.image-subject{
			border-radius: 50%;
			-webkit-transition: -webkit-transform .8s ease-in-out;
			transition: -webkit-transform .8s ease-in-out;
			padding: 5%;
		}

		.image-subject:hover{
			-webkit-transform: rotate(360deg);
			transform: rotate(360deg);
		}

		.padding-lateral{
			padding-right: 10%;
			padding-left: 10%;
		}

		.padding-description{
			padding-right: 3%;
			padding-left: 3%;
		}
		
		.padding-lateral-icons{
			padding-right: 5%;
			padding-left: 5%;
			opacity: 0.6;
		}

		.padding-lateral-icons:hover{
			opacity: 1;
			-webkit-transition: opacity .5s ease-in-out;
			transition: opacity .5s ease-in-out;
		}
		.droptown{
			position: absolute;
			top: 100%;
			background-color: #F5F5F5;
			display: block;
			z-index: 999;
		}
		
		.margin{
			padding-top: 5%;
			padding-bottom: 5%;
		}

		.margin10{
			padding-top: 7%;
			padding-bottom: 7%;
		}

		.color-cursos{
			/*background-color: #3273DC;*/
			background-color: #38A9F6;
		}

		.color-cursos:hover{
			background-color: #2E8CCC;
			-webkit-transition: background-color .6s ease-in-out;
			transition: background-color .5s ease-in-out;
		}

		.color-curso-selected{
			background-color: #2E8CCC;
		}

		.fixeded{
			position: fixed;
		}

		.scroll{
			overflow-y: scroll;
			height: 100%;
		}

		::-webkit-scrollbar{
			display: none;
		}

		.border-bye{
			border-top: 0px !important;
			margin-top: 0px !important;
			padding-top: 0px !important;
		}

		.icon-desplegable:hover{
			color: #38A9F6;
			-webkit-transition: color .5s ease-in-out;
			transition: color .5s ease-in-out;
		}

		.padding-icons{
			padding-left: 2%;
		}

	</style>

	<section class="columns remove-margin">

		<div class="column is-one-quarter is-fullheight is-fullwidth notification has-text-centered remove-margin fixeded scroll" style="background-color: #38A9F6; color:white">

			<!--<h2 class="title top">{{subject.title}} ({{courses|length}})</h2>-->
			<h5 class="title top">Selecciona un curso!</h5>
			<hr>

			<div class="container" style="text-align:justify">
			{% if courses %}
				<ul>
				{% for course in courses %}
					
					{% if course_selected.title == course.title %}

						<a href="{%url 'courses:subject_detail_with_course' subject.slug course.slug%}">
							<!--<div class="card is-fullwidth top-all color-curso-selected">
								<div class="card-content">
									<div class="content" style="color: white">
										<p class="title is-4"><strong>{{course.title}}</strong></p>
										<p class="subtitle is-6 top-mitad">{{course.overview}}</p>
									</div>
								</div>
							</div>-->
							<li>
								<div class="content padding-lateral margin10 color-curso-selected" style="color: white">
										<p class="title is-4"><strong>{{course.title}}</strong></p>
										<p class="subtitle is-6 top-mitad">{{course.overview}}</p>
								</div>
							</li>
						</a>

					{% else %}

					<a href="{%url 'courses:subject_detail_with_course' subject.slug course.slug%}">
						<!--<div class="card is-fullwidth top-all color-cursos">
							<div class="card-content">
								<div class="content" style="color: white">
									<p class="title is-4"><strong>{{course.title}}</strong></p>
									<p class="subtitle is-6 top-mitad">{{course.overview}}</p>
								</div>
							</div>
						</div>-->
						<li>
							<div class="content padding-lateral margin10 color-cursos" style="color: white">
										<p class="title is-4"><strong>{{course.title}}</strong></p>
										<p class="subtitle is-6 top-mitad">{{course.overview}}</p>
							</div>
						</li>
					</a>

					{% endif %}
				{% endfor %}
			</ul>
			{% else %}

				<h1 class="title" style="text-align:center;">Aún no hay cursos :(</h1>
			{% endif %}
			</div>
		</div>

		<div class="column remove-margin" style="margin-left:25% !important;">
			<article class="media">
				<div class="media-left remove-margin" id="button-languajes" style="position:relative;">
					<p class="remove-margin">
						<a href="{% url 'courses:subject_detail' subject.slug %}"><img src="{{subject.image.url}}" class="image is-64x64 image-subject icon-desplegable"></a>
					</p>
				<div class="droptown remove-margin" style="display: none; background-color: white;">
					<ul class="padding-icons">
						{% for languaje in languajes %}
							<li class="margin">
							<a href="{%url 'courses:subject_detail' languaje.slug%}">
								<img src="{{languaje.image.url}}" alt="" class="image is-64x64 image-subject">
							</a>
							</li>
						{% endfor %}
					</ul>
				</div>
				</div>
				<span class="icon is-medium" style="padding-top: 1%;">
						<i class="fa fa-sort-down icon-desplegable"></i>
						</span>
				
			{% if course_selected %}
					
				<div class="media-content">
					<div class="content columns" style="text-align:center; padding-top: 2%;">
						<div class="column is-8">
							<h1 class="title" style="padding-right:64px;">{{course_selected.title}}</h1>	
						</div>
						<span class="column is-3" style="text-align:justify; padding-top: 2%;">
					<a href="{%url 'user_detail' course_selected.owner.username%}"><p class="subtitle">Instructor: {{course_selected.owner}}</p></a></span>
					</div>
				</div>
				<hr>
			</article>

			<div class="container padding-lateral" style="position:relative; padding-bottom:5%; padding-top: 1em;">
				{% for module in modules %}

					<div class="box open_items" id="{{module.order}}">
						<article class="media">
							<div class="media-left column is-4">
								<div class="content">
									<h3 class="title">{{module.title}}</h3>
								</div>
							</div>
							<div class="media-content column is-7">
								<div style="padding-top:1%;" class="column is-10">
									<progress style="position:relative" class="progress is-success" value="80" max="100"><span style="position:absolute;">80%</span></progress>
								</div>
							</div>
						</article>
						<article class="media border-bye">
							<div class="media-content column is-12">
								<p class="subtitle is-5">{{module.description}}</p>
							</div>
						</article>
						<article class="media top-mitad" id="{{module.order}}_droptown" style="display:none">
							<div class="media-content">
								{% if module.contents.all.count != 0 %}
									
								{% for content in module.contents.all %}
									<a href="#">
										<img src="/media/images/icons/{{content.content_type}}.svg" alt="" class="padding-lateral-icons">
									</a>
								{% endfor %}
								
								{% else %}
									<p>No hay contenido en este módulo :(</p>
								{% endif %}
							</div>
						</article>
					</div>
				{% endfor %}
			</div>
			{% else %}
				<div class="media-content">
					<div class="content" style="text-align: center; padding-top: 2%;">
						<h1 class="title" style="padding-right:64px;">{{subject.title}}</h1>
					</div>
				</div>
				<hr>
			</article>
				<div class="container" style="position:absolute; text-align:justify; padding-top: 1em;">
					<div class="video" style="text-align:center;">
						{% video subject.video 'small' %}
					</div>
					<h1 class="title is-5 top-mitad padding-lateral">{{subject.description}}</h1>
				</div>
			{% endif %}
		</div>
		
	</section>
	
	
{% endblock content %}
{% block domready %}
		
		$('.icon-desplegable').on('click', function(){
			console.log("Hola");
			$('.droptown').slideToggle();
		});

		$('.open_items').on('click',function(){
			let id = $(this).attr('id');
			console.log(id);
			$('#'+id+'_droptown').slideToggle('slow');
		});

	{% endblock domready %}

courses/templates/subjects/list.html
{% extends "base.html" %}
{% block content %}
	<h2>Para iniciar, selecciona un lenguaje de tu interés!</h2>	
		<br><br><br>
		<div class="container">
			<div class="columns is-multiline">
				{% for subject in subjects %}
					<div class="column is-half">
						<a href="{%url 'courses:subject_detail' subject.slug%}">
						<div class="box">
							<article class="media">
								<div class="media-left">
									<figure class="image is-64x64">
										<img src="{{subject.image.url}}" alt="">
									</figure>
								</div>
								<div class="media-content">
									<div class="content">
										<h3 class="title">{{subject.title}}</h3>
										<p>{{subject.no_courses}} cursos</p>
									</div>
								</div>
							</article>
						</div>
						</a>
					</div>
				{%endfor%}
			</div>
		</div>
	</div>

{% endblock content %}