galaxy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import urls as mainUrls
from courses import urls as coursesUrls
from accounts import urls as accountsUrls
from django.views.static import serve
from django.conf import settings
from django.contrib.auth.views import password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from students import urls as studentsUrls


urlpatterns = [
    
    url(r'^students/',
        include(studentsUrls, namespace="students")),

    url(r'^accounts/', 
        include(accountsUrls)),

    url(r'^admin/', admin.site.urls),

    url(r'^courses/',
        include(coursesUrls, namespace="courses")),

    url(r'^',
        include(mainUrls)),

    url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root':settings.MEDIA_ROOT}
        ),
]

main/urls.py
from django.conf.urls import url


urlpatterns = [

]

students/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url(r'^register/$',
		views.StudentRegistrationView.as_view(),
		name="student_registration"),

	url(r'^enroll-course/$',
		views.StudentEnrollCourseView.as_view(),
		name="student_enroll_course"),

# Lista de cursos comprados por usuario y detalle


	url(r'^course/(?P<pk>\d+)/(?P<module_id>\d+)/$',
		views.StudentCourseDetailView.as_view(),
		name="student_course_detail_module"),

	url(r'^course/(?P<pk>\d+)/$',
		views.StudentCourseDetailView.as_view(),
		name="student_course_detail"),

	url(r'^courses/$',
		views.StudentCourseListview.as_view(),
		name="student_course_list"),
]

students/models.py
from django.db import models

# Create your models here.

students/forms.py
from django import forms
from courses.models import Course


class CourseEnrollForm(forms.Form):
	course = forms.ModelChoiceField(
		queryset=Course.objects.all(),
		widget=forms.HiddenInput
		)
	

students/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

from braces.views import LoginRequiredMixin
from .forms import CourseEnrollForm

# para dar acceso al contenido una vez enrollado
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from courses.models import Course




class StudentRegistrationView(CreateView):
	template_name = 'students/student/registration.html'
	form_class = UserCreationForm
	success_url = reverse_lazy('students:student_course_list')

	def form_valid(self, form):
		result = super(StudentRegistrationView, self).form_valid(form)
		cd = form.cleaned_data
		user = authenticate(username=cd['username'], password=cd['password1'])
		login(self.request, user)
		return result


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
	course = None
	form_class = CourseEnrollForm

	def form_valid(self, form):
		self.course = form.cleaned_data['course']
		self.course.students.add(self.request.user)
		return super(StudentEnrollCourseView, self).form_valid(form)

	def get_success_url(self):
		return reverse_lazy('students:student_course_detail', args=[self.course.id])

# Mostramos al usuario los cursos que ha comprado

class StudentCourseListview(LoginRequiredMixin, ListView):
	model = Course
	template_name = 'students/course/list.html'

	def get_queryset(self):
		qs = super(StudentCourseListview, self).get_queryset()
		return qs.filter(students__in=[self.request.user])

class StudentCourseDetailView(DetailView):
	model = Course
	template_name = 'students/course/detail.html'

	def get_queryset(self):
		qs = super(StudentCourseDetailView, self).get_queryset()
		return qs.filter(students__in=[self.request.user])

	def get_context_data(self, **kwargs):
		context = super(StudentCourseDetailView, self).get_context_data(**kwargs)
		# traer el curso
		course = self.get_object()
		if 'module_id' in self.kwargs:
			# traemos el modulo actual
			context['module'] = course.modules.get(id=self.kwargs['module_id'])
		else:
			# traemos el primer modulo
			context['module'] = course.modules.all()[0]
		return context

students/templates/students/course/detail.html
{%extends 'base.html'%}

{%block content%}

	<h1>
		{{module.title}}
	</h1>

	<div class="contents">
		<h3>Modules</h3>
		<ul id="modules">
			{%for m in object.modules.all%}
				<li data-id="{{m.id}}" {%if m == module%} class="selected"{%endif%}>
					<a href="{%url 'students:student_course_detail_module' object.id m.id%}">
						<span>Module <span class="order">
							{{m.order|add:1}}
						</span></span>
						<br>
						{{m.title}}
					</a>
				</li>
			{%empty%}
			<li>Aún no hay modulos</li>
			{%endfor%}
		</ul>
	</div>

	<div class="module">
		{%for content in module.contents.all%}
			{%with item=content.item%}
				<h2>{{item.title}}</h2>
				{{item.render}}
			{%endwith%}
		{%endfor%}
	</div>

{%endblock content%}

students/templates/students/course/list.html
{%extends 'base.html'%}

{%block content%}

	<h1>Mis cursos</h1>

	<div class="module">
		{%for course in object_list%}
		<div class="course-info">
			<h3>{{course.title}}</h3>
			<p>
				<a href="{%url 'student_course_detail' course.id%}">
					Acceder al contenido
				</a>
			</p>
		</div>
		{%empty%}
		<p>
			No haz comprado ningun curso aún
			<a href="{%url 'course_list'%}">
				Explorar cursos
			</a> para comprar alguno.
		</p>
		{%endfor%}
	</div>

{%endblock content%}